# Generated by Django 4.0 on 2022-10-23 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='teams',
        ),
        migrations.AddField(
            model_name='match',
            name='match_round',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='match_round',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MatchRound',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
