# Generated by Django 4.0 on 2022-10-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_comment_created_on_match_away_team_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('matches_played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('goal_difference', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'table_22_23',
                'managed': False,
            },
        ),
    ]
