# Generated by Django 4.0 on 2022-10-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_alter_match_away_team_alter_match_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo_url',
            field=models.URLField(null=True),
        ),
    ]
