# Generated by Django 4.0 on 2022-10-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_team_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='team',
            name='home_stadium',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stadium',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
