# Generated by Django 4.0 on 2022-10-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_remove_comment_user_remove_match_stadium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
    ]
