# Generated by Django 4.0 on 2022-10-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_remove_comment_user_id_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.CharField(default='ss', max_length=200),
            preserve_default=False,
        ),
    ]
