# Generated by Django 4.0 on 2022-10-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_remove_match_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='game_played',
        ),
    ]
